### ISSUE TITLE
Automate Windows Restart and Environment Variables

### ISSUE THREAD

**Issue by rafaheringer** [mszcool/devmachinesetup#2]
"It automates the setup process as far as possible, but not entirely. The reason for that is that some installations modify environment variables or even require a re-start. "

For this consider using the BoxStarter solution: http://blog.zerosharp.com/provisioning-a-new-development-machine-with-boxstarter/

**Comment by mszcool** [comment]
Restart is only necessary in prepOS and refreshenv function added
